language: bash

sudo: required

before_install:
- openssl aes-256-cbc -K $encrypted_9155b263749f_key -iv $encrypted_9155b263749f_iv
  -in deploy-key.enc -out deploy-key -d

install:
 - sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
 - opam install dune reason js_of_ocaml tyxml deriving ppx_deriving reactiveData ocp-indent camomile js_of_ocaml-tyxml menhir oUnit
 - opam install coq

script:
  - bash .travis-ci.sh

#Only run on Master currently
branches:
  only:
  - master
