name: Deploy examples-cardstack
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: grab the code # STEP 1
        uses: actions/checkout@v2
        with:
          path: source
      - name: cache/retrieve build environment # STEP 1.5
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: './source/.opam'
          key: ${{ runner.os }}-modules-${{ hashFiles('./source/opam.export') }}
      - name: install dependencies and build # STEP 2
      #- run: sudo add-apt-repository --yes ppa:avsm/ppa
      #- run: sudo apt update
      - run: |
          sudo apt --assume-yes install m4 opam
          export OPAMYES=1
          opam init --compiler=ocaml-base-compiler.4.08.1
          eval $(opam env); make deps 
          eval $(opam env); make release
        working-directory: ./source
      - name: grab the website # STEP 3
        uses: actions/checkout@v2
        with:
          repository: hazelgrove/build
          token: ${{ secrets.ACCESS_TOKEN }} # TODO: reduce permissions
          path: server
      - name: clear old build # STEP 4
        run: if [ -d "test-branch-name" ] ; then rm -rf "test-branch-name" ; fi 
        working-directory: ./server
      #- run: ls -a; touch plargstukha.txt #temp remove
      #  working-directory: ./server
      - name: copy new build # STEP 5
        run: mkdir "./server/test-branch-name" && cp -r "./source/_build/default/src/hazelweb/www/*" "./server/test-branch-name"
        #working-directory: ./server
      - name : commit website aka deploy # STEP 6
        run: |
          ls -a
          git config user.name github-deploy-action
          git config user.email hazel-deploy@hazel.org
          git status
          git add -A
          git status
          git commit -m "github-deploy-action"
          git push
        working-directory: ./server
      #- name: Debugging with ssh
      #  uses: lhotari/action-upterm@v1

      # before_install

      # deploy
      #- name: deploy
      #  if: ${{ github.ref == 'refs/heads/github-actions-test' }}
      #  run: bash .travis-deploy.sh # UPDATE MEEEEE
      #  env: TRAVIS_BRANCH: ${{ github.ref }}

# if git commit -m "Github Deploy Action" --allow-empty; then git push origin master # deploy
