name: Deploy examples-cardstack
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache opam
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: '/home/runner/.opam'
          key: ${{ runner.os }}-modules-${{ hashFiles('opam.export') }}
      # before_install
      #- run: sudo add-apt-repository --yes ppa:avsm/ppa
      #- run: sudo apt update
      - run: sudo apt --assume-yes install m4 opam

      # install
      - run: export OPAMYES=1
      - run: opam init --compiler=ocaml-base-compiler.4.08.1
      - run: eval $(opam env)
      #- run: export PATH="/home/runner/.opam/4.08.1/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
      - run: make deps   
      # script

      - run: eval $(opam env)
      - run: make release
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1
      # deploy
      #- name: deploy
      #  if: ${{ github.ref == 'refs/heads/github-actions-test' }}
      #  run: bash .travis-deploy.sh # UPDATE MEEEEE
      #  env: TRAVIS_BRANCH: ${{ github.ref }}


