name: Deploy examples-cardstack
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache opam
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: '/home/runner/.opam'
          key: ${{ runner.os }}-modules-${{ hashFiles('opam.export') }}
      # before_install
      #- run: sudo add-apt-repository --yes ppa:avsm/ppa
      #- run: sudo apt update
      - run: sudo apt --assume-yes install m4 opam

      # install
      - run: export OPAMYES=1
      - run: opam init --compiler=ocaml-base-compiler.4.08.1
      #- run: echo "/home/runner/.opam/ocaml-base-compiler.4.08.1/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" >> $GITHUB_PATH
      #- run: eval $(opam env)
      #- run: export PATH="/home/runner/.opam/4.08.1/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
      # script
      - run: which dune
        env: #duplicated effect of eval $(opam env)
          OPAM_SWITCH_PREFIX: '/home/runner/.opam/ocaml-base-compiler.4.08.1'
          CAML_LD_LIBRARY_PATH: '/home/runner/.opam/ocaml-base-compiler.4.08.1/lib/stublibs:Updated by package ocaml'
          OCAML_TOPLEVEL_PATH: '/home/runner/.opam/ocaml-base-compiler.4.08.1/lib/toplevel'
          MANPATH: ':/home/runner/.opam/ocaml-base-compiler.4.08.1/man'
          PATH: '/home/runner/.opam/ocaml-base-compiler.4.08.1/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'

      - run: make deps 

      - run: make release
        env: #duplicated effect of eval $(opam env)
          OPAM_SWITCH_PREFIX: '/home/runner/.opam/ocaml-base-compiler.4.08.1'
          CAML_LD_LIBRARY_PATH: '/home/runner/.opam/ocaml-base-compiler.4.08.1/lib/stublibs:Updated by package ocaml'
          OCAML_TOPLEVEL_PATH: '/home/runner/.opam/ocaml-base-compiler.4.08.1/lib/toplevel'
          MANPATH: ':/home/runner/.opam/ocaml-base-compiler.4.08.1/man'
          PATH: '/home/runner/.opam/ocaml-base-compiler.4.08.1/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1
      # deploy
      #- name: deploy
      #  if: ${{ github.ref == 'refs/heads/github-actions-test' }}
      #  run: bash .travis-deploy.sh # UPDATE MEEEEE
      #  env: TRAVIS_BRANCH: ${{ github.ref }}


