name: Deploy examples-cardstack
on:
  push:
    branches:
    - github-actions-test   #set to all
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # before_install
      #- run: sudo add-apt-repository --yes ppa:avsm/ppa
      - run: sudo apt update
      - run: sudo apt --assume-yes install m4 opam
      # install
      - run: export OPAMYES=1
      - run: opam init --compiler=ocaml-base-compiler.4.08.1
      - run: eval $(opam env)
      - run: ls
      - run: make deps   
      # script
      - run: make release
      # deploy
      - name: deploy
        if: ${{ github.ref == 'refs/heads/github-actions-test' }}
        run: bash .travis-deploy.sh


